export const activityData = [
    {
        "Id": "C4D6FA01-DCD0-4195-A7FF-019EA5F336C6",
        "BasicActivity": "Personal exercise",
        "ActivityTime": "2020-02-18T18:28:15.736666Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": "Watches",
        "RecognizedActivity": "Unknown",
        "LabelsJson": "[{\"Label\":\"Electronic device\",\"Score\":0.8993125557899475},{\"Label\":\"Technology\",\"Score\":0.8870062232017517},{\"Label\":\"Gadget\",\"Score\":0.8008481860160828},{\"Label\":\"Electronics\",\"Score\":0.7308112978935242},{\"Label\":\"Finger\",\"Score\":0.6978344917297363},{\"Label\":\"Watch\",\"Score\":0.6840049624443054},{\"Label\":\"Watch phone\",\"Score\":0.6380442380905151},{\"Label\":\"Portable communications device\",\"Score\":0.613295316696167},{\"Label\":\"Wrist\",\"Score\":0.5157835483551025}]",
        "ScreenshotFindingsJson": "{\"Steps\":null}",
        "ScreenshotFindingsDetailsJson": "{\"Language\":\"ro\",\"TextAngle\":0,\"Orientation\":\"NotDetected\",\"Regions\":[{\"BoundingBox\":\"215,309,70,91\",\"Lines\":[{\"BoundingBox\":\"215,309,46,14\",\"Words\":[{\"BoundingBox\":\"215,309,46,14\",\"Text\":\"FEB\\u002720\"}]},{\"BoundingBox\":\"258,386,27,14\",\"Words\":[{\"BoundingBox\":\"258,386,27,14\",\"Text\":\"Am\"}]}]},{\"BoundingBox\":\"169,364,37,94\",\"Lines\":[{\"BoundingBox\":\"169,364,37,16\",\"Words\":[{\"BoundingBox\":\"169,364,37,16\",\"Text\":\"A29\"}]},{\"BoundingBox\":\"171,441,31,17\",\"Words\":[{\"BoundingBox\":\"171,441,31,17\",\"Text\":\"652\"}]}]}]}",
        "ActivityDetails": null,
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 20,
    },
    {
        "Id": "FECB1916-915D-4416-85B1-388D667186E4",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-07-10T06:30:35Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Movement activity completed\",\"SubcategoryType\":\"Strength excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "04B6E653-195E-44B1-A86D-074CABCFC642",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-07-14T18:24:52Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Movement activity completed\",\"SubcategoryType\":\"Strength excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "4F7E66C0-C31C-4076-9E05-1B95A88777CB",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-07-25T20:08:54Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Nutrition activity completed\",\"SubcategoryType\":\"HealthyEating  completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "772D8E5B-0E06-4B1B-BFA2-2B4EBF1BD804",
        "BasicActivity": "Nutrition programme",
        "ActivityTime": "2020-07-27T05:28:05Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Program completed\",\"CategoryType\":\"Nutrition activity completed\",\"SubcategoryType\":\"HealthyEating  completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Nutrition",
        "points": 50,
    },
    {
        "Id": "DA22B433-A91A-4606-A73A-0F8891B901E2",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-08-11T21:37:58Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Mindfulness activity completed\",\"SubcategoryType\":\"Motivation excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "3D594AE6-BE8C-4CF2-8CC7-00F9CA742F90",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-08-12T21:00:47Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Mindfulness activity completed\",\"SubcategoryType\":\"Motivation excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "16F35FFC-1833-4BAE-8390-37AECDEF1987",
        "BasicActivity": "Weekly Bonus",
        "ActivityTime": "2020-08-12T21:00:47Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Loyalty",
        "points": 30,

    },
    {
        "Id": "C9FD7B44-C24A-428F-A6A6-34583B58FFF5",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-08-24T20:39:17Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Movement activity completed\",\"SubcategoryType\":\"Strength excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "5DE7E074-45C6-4F7B-8D59-20964ED8F926",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-08-30T15:12:33Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Mindfulness activity completed\",\"SubcategoryType\":\"Motivation excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : false,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "405D7F27-DD4F-40FB-A272-3D068F4E8107",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-09-03T19:10:04Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Nutrition activity completed\",\"SubcategoryType\":\"HealthyEating  completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "81F63851-8017-4283-BB00-0D8BF440C56E",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-09-12T11:53:13Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Nutrition activity completed\",\"SubcategoryType\":\"HealthyEating  completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "82725D33-C3F5-4F3D-A2F5-3B4458335206",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-09-16T21:06:59Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Mindfulness activity completed\",\"SubcategoryType\":\"Motivation excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "C8A7ACBD-3B7D-46AE-A253-096EC9A2DA91",
        "BasicActivity": "Daily session",
        "ActivityTime": "2020-09-17T07:31:29Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "{\"ActivityType\":\"Session completed\",\"CategoryType\":\"Mindfulness activity completed\",\"SubcategoryType\":\"Motivation excercise completed\"}",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Fitness",
        "points": 10,
    },
    {
        "Id": "C3900F7A-09F5-4382-8F08-137BD32B17B0",
        "BasicActivity": "Weekly Bonus",
        "ActivityTime": "2020-09-17T07:31:29Z",
        "Gender": "male",
        "Age": 29,
        "ImageClass": null,
        "RecognizedActivity": null,
        "LabelsJson": null,
        "ScreenshotFindingsJson": null,
        "ScreenshotFindingsDetailsJson": null,
        "ActivityDetails": "",
        "REF_PARTNER": "9999434",
        "approved" : true,
        "category": "Loyalty",
        "points": 30,
    }
]